### ISSUE TITLE
error in comment_author_alias.py

### ISSUE THREAD

**Issue by gurubert** [makanakoeln/projects#2]
The painter in comment_author_alias.py uses a obsoleted method. The following patch corrects this:

```
--- comment_author_alias.py.orig	2016-12-02 07:17:55.104039977 +0100
+++ comment_author_alias.py	2017-10-18 11:20:21.955279124 +0200
@@ -2,7 +2,7 @@
     user_alias_query = "GET contacts\n" \
                        "Columns: alias\n" \
                        "Filter: name = %s\n" % userid
-    user_alias = html.live.query(user_alias_query)
+    user_alias = sites.live().query(user_alias_query)
     if user_alias:
         return user_alias[0][0]
     else:
```

**Comment by makanakoeln** [comment]
Thanks, will fix this soon

**Comment by makanakoeln** [comment]
Works in cmk 1.4.0p7, since what version this method is obsolet? To make two mkp...

**Comment by makanakoeln** [comment]
fixed

**Comment by gurubert** [comment]
Unfortunately you have missed the brackets after sites.live in the code published on https://github.com/makanakoeln/projects/blob/master/local/share/check_mk/web/plugins/views/comment_author_alias.py

**Comment by makanakoeln** [comment]
Hi,
stupid mistake. Fixed that.
thanks!
