### ISSUE TITLE
last_windows_updates.vbs incompatible to Windows 10

### ISSUE THREAD

**Issue by LevonTostig** [makanakoeln/projects#5]
As far as I can see the registry key `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\Results\Install\LastSuccessTime` does not exist in Windows 10 anymore. Unfortunately, up until now, I could find where MS hid an equivalent.

**Comment by makanakoeln** [comment]
there is no registry key any more. Think i reworked this as powershell but have to look if i can find it.
